config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :attachmes
  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end
  root 'pages#home'
  resources :projects do 
    resources :attachmes

  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachme.rb
class Attachme < ApplicationRecord
  belongs_to :project
  has_one_attached :upload

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/post.rb
class Post < ApplicationRecord
    default_scope { order created_at: :desc }
    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :body, presence: true, length: {minimum: 10, maximum: 1000}
    belongs_to :user
    has_many :comments, dependent: :destroy 
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :attachme, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy 
         has_many :comments, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachmes_controller.rb
class AttachmesController < ApplicationController
  before_action :set_project
  before_action :set_attachme, only: [:show, :edit, :update, :destroy]


  # GET projects/1/tasks
  def index
    @attachmes = @project.attachme

  end

  # GET projects/1/tasks/1
  def show
      
  end

  # GET projects/1/tasks/new
  def new
    @attachme = @project.attachme.build
    @attachmes = @project.attachme
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @attachme = @project.attachme.build(attachme_params)

    if @attachme.save
      redirect_to new_project_attachme_path
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @attachme.update(attachme_params)
      redirect_to(@attachme.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @attachme.destroy
    redirect_to root_path
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_attachme
      @attachme = @project.attachme.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def attachme_params
      params.require(:attachme).permit(:name, :attachment, :upload)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save 
           redirect_to post_path(@post)
        else
            flash[:notice] = "Comment has been created"
            redirect_to post_path(@post)
  end        
end

def destroy
     @commet = @post.comments.find(params[:id])
     @commet.destroy
     redirect_to post_path(@post)
end
def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@post) }
      else
        format.html { redirect_to post_url(@post), alert: 'Comment was not updated!' }
      end
    end
  end
private  

def set_post
    @post = Post.find(params[:post_id])
end

def comment_params
 params.require(:comment).permit(:body)
end
end   

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

#   daf about
# end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    # views =@post.views + 1
    # @post.views = views
    # @post.save
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end
 
 # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit;end
  
  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
       
       respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachmes_helper.rb
module AttachmesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/attachmes/_attachme.html.erb
<div id="<%= dom_id attachme %>">
  <p>
    <strong>Name:</strong>
    <%= attachme.name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= attachme.project_id %>
  </p>

</div>

app/views/attachmes/_form.html.erb
<%= form_for([@attachme.project, @attachme]) do |f| %>
  <% if @attachme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachme.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @attachme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= f.label :name %>   
      <%= f.text_field :name %>   
      <br><br>   
      <%= f.label :upload %>   
      <%= f.file_field :upload %>
      <br>   
      <%= f.submit "Save" %>   
<% end %>

app/views/attachmes/edit.html.erb
<h1>Editing attachme</h1>

<%= render "form", attachme: @attachme %>

<br>

<div>
  <%= link_to "Show this attachme", @attachme %> |
  <%= link_to "Back to attachmes", attachmes_path %>
</div>

app/views/attachmes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attachmes</h1>

<div id="attachmes">
  <% @attachmes.each do |attachme| %>
    <%= render attachme %>
    <p>
      <%= link_to "Show this attachme", attachme %>
    </p>
  <% end %>
</div>

<%= link_to "New attachme", new_attachme_path %>

app/views/attachmes/new.html.erb
<h1 align="center">Uploader</h1> <br> 
<div class="container" align="center">
<%= form_for([@attachme.project, @attachme]) do |f| %>
  <% if @attachme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachme.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @attachme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
      <%= f.file_field :upload %> <br> <br>

      <%= f.submit "Add", class:"btn btn-primary btn_add"%> <br> 
      
      <% end %>
    
    
              <% @attachmes.each do |attachme| %>
                <% if attachme.upload.attached? %>
                                <% if  attachme.upload.image?%> <br>
                                    <%= link_to image_tag(attachme.upload, class: "img_upload"),  rails_blob_path(attachme.upload, disposition: "attachment") %> <br>
                                    <% elsif attachme.upload.audio? %>
                                   <%= attachme.upload.filename %>
                                      <audio controls>
                                       <source src=" <%= rails_blob_url(attachme.upload, disposition: "attachment") %>" type="audio/mpeg"/> <br>
                                       </audio> <br>
                                       <% else %>
                                       <%= link_to attachme.upload.filename,  rails_blob_path(attachme.upload, disposition: "attachment") %> <br>
                                        <% end %> <br> 

           

                                            <%= link_to 'Destroy', [attachme.project, attachme], 'data-turbo-method': :delete, class: "more-link"  %> <br>

            <% end %>
            
            <% end %>
          <br><br>



<style>

.img_upload{
   border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}

</style>

<%= link_to project_path(@project.id) do %>
<button class="btn btn-danger">Back</button>

<% end %>
</div>

app/views/attachmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attachme %>

<div>
  <%= link_to "Edit this attachme", edit_attachme_path(@attachme) %> |
  <%= link_to "Back to attachmes", attachmes_path %>

  <%= button_to "Destroy this attachme", @attachme, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %> container"
    style="border: 1px solid black; padding: 1em; margin: 1em;">
  <p><i class="bi bi-person"></i> <%= comment.user.email %></p><br />
  <% if (comment.updated_at - comment.created_at) > 1 %>
    <span><i class="bi bi-pencil-square"></i> <%= time_ago_in_words(comment.updated_at) %> ago</span>
  <% else %>
    <span><i class="bi bi-pen-fill"></i> <%= time_ago_in_words(comment.created_at) %> ago</span>
  <% end %>
  <% if current_user == comment.user %>
    <div class="btn-group float-end">
      <%= link_to "Edit", nil, remote: true, class:"btn btn-warning",
      data: {
        controller: "comments",
        action: "comments#toggleForm",
        comments_form_param: "edit-form-#{comment.id}",
        comments_body_param: "comment-body-#{comment.id}",
        comments_edit_param: "edit-button-#{comment.id}"
      },
      id: "edit-button-#{comment.id}" %>
      <%= button_to "Delete", [post, comment], style: "margin-left: 10px", class:"btn btn-danger", method: :delete %>
    </div>
    <div id="edit-form-<%= comment.id%>" class="d-none">
      <%= render 'comments/form',
       post: @post,
       comment: comment,
       submit_label: "Update" %>
    </div>
  <% end %>
  <hr />
  <div id="comment-body-<%= comment.id %>">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
  <div class="form-control">
    <%= f.rich_text_area :body %>
    <%= f.submit submit_label, class: "btn btn-primary mt-1" %>
  </div>
<% end %>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
     <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
       <ul class="navbar-nav " style="margin-right: 72px;">
       
       <% if current_user.admin == true %>
         <%= link_to "Admin Dashboard", "/admin",   class:"nav-link " %>
       <% end %>
    <%= link_to "New Projects", projects_path,   class:"nav-link " %>
     <%= link_to "New Post", posts_path, class:"nav-link " %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= current_user.email %>
          </a>
          
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit Account", edit_user_registration_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basecamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render "layouts/navbar" if user_signed_in? %>
     <% if  notice %>
<%= render "layouts/alert" %>
   <% end %>
    <%= yield %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<% else %>
<div align="center" style="margin-top: 400px;">
    <%= link_to "Sign Up!", new_user_registration_path , class:"btn btn-primary" %>
  
     <%= link_to "Login", new_user_session_path , class:"btn btn-primary"%>
     </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class: "form-control"%>
  </div>  <br>
  <%= form.number_field :user_id, id: :post_user_id, value: current_user.id, type: :hidden %>


  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <h2><%= post.title %></h2>
   <p>Posted by <%= post.user.email %> </p> 
    <h6><%= pluralize(post.views, "view") %></h6>
    <div>
    <strong>Body:</strong>
    <%= post.body %>
   </div>
</div>

app/views/posts/edit.html.erb
<div class="container"style="width: 36%; text-align: center; justify-content: center; ">

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

</div>

app/views/posts/index.html.erb
<div class="container"><%= link_to "New Post", new_post_path, class: "btn btn-primary", style: "float: right; margin-top: 7px;" %>

<h1 align="center">Posts</h1> <br> <br>


<div class="row" style="margin-left: 10px;">
  <% @posts.each do |post| %>
<div class="card" style="width: 18rem; margin-left: 7px;" >
  <div class="card-body">
     <h5 class="card-title"><%= post.title %></h5>
<p class="card-text"><%= post.body %>.</p>
<p class="card-text">Author <i class="bi bi-person"></i> <%= post.user.email %></p>
<p class="card-text"><i class="bi bi-eye-fill"></i> <%= post.views %> views</p>
        <p href="#" class="card-link"><%= link_to post do %>
    <p>Show All</p>
    </p><% end %>
  </div>
</div>
 <% end %>
</div> <br> <br>

app/views/posts/new.html.erb
<div class="container"style="width: 36%; text-align: center; justify-content: center; ">

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container"> 
<p style="float: right;">
<%= link_to "Back to posts", posts_path , style: "float: right;"%>
  <%= button_to "Destroy this post", @post, method: :delete, style: "float: right;  margin-right: 10px;", class: "btn btn-danger"%>
    <%= link_to edit_post_path(@post) do %>
  <button class="btn btn-primary" style="float: right; margin-right: 10px;">Edit</button>
  <% end %>
</p>
<h2 align="center"><%= @post.title %></h2>
   <h5 align="center" style="margin-left: -296px;"><i class="bi bi-pen"></i><%= @post.user.email %> </h5> 
    <h6  align="center" style="margin-left: -296px;"><i class="bi bi-eye"></i> <%= pluralize(@post.views, "view") %></h6>
    <div>
    <%= simple_format @post.body %>
   </div> <br> <br>

</div>


<div class="container" style="width: 36%; float: left;">
  <%= render 'comments/form', 
    post: @post, 
    comment: @post.comments.build,
    submit_label: "Reply" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    post: @post, 
    comment: comment %>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
  <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>

  </div><br>

  <div>
    <%= form.submit class: "btn btn-info"%>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<div class="container"style="width: 36%; text-align: center;">

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

</div>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= link_to "New project", new_project_path, class: "btn btn-primary", style: "float: right" %>

<div class="row" style="margin-left: 10px;">
  <% @projects.each do |project| %>
  <% if project.user.id == current_user.id%>
<div class="card" style="width: 18rem; margin-left: 7px;" >
  <div class="card-body">
     <h5 class="card-title"><%= project.name %></h5>
<p class="card-text"><%= project.description %>.</p>
        <p href="#" class="card-link"><%= link_to project do %>
    <i class="bi bi-eye"></i>
    </p><% end %>
  </div>
</div>
 <% end %>
 <% end %>
</div> <br> <br>

app/views/projects/new.html.erb
<div class="container"style="width: 36%; text-align: center;">

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>
</div>

app/views/projects/show.html.erb
<div class="container">

    <h1 align="center"><%= @project.name %></h1>

<div>
  <%= link_to "Edit this project", edit_project_path(@project), class:"btn btn-primary"%>
<div style="float: right;">
  <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger"%>
  </div>
      <h4><p align="center"><%= link_to 'New Attachment', new_project_attachme_path(@project.id), class: 'btn btn-info' %></p></h4> 

</div>
 <br><br><br><br>
</div> 
<div align="center">
<%= link_to "Back to projects", projects_path, class: 'btn btn-primary'%>
</div>